name: aci
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray=2024.02.0
  - bottleneck
  - requests
  - netCDF4  # without version to get the latest compatible version
  - dask
  - psutil
  - pandas
  - coverage
  
