name: aci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5  # or a compatible version
  - scipy=1.13.0  # or a compatible version
  - netcdf4  # without version to get the latest compatible version
  - xarray=0.20.0
  - h5netcdf
  - jupyter
  - matplotlib
  - bottleneck
  - seaborn
  - cdsapi

